sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip # The latest version of Go.

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tmux

script:
  - export GOROOT=$(go env GOROOT)
  - ./.travis.gofmt.sh
  - go get golang.org/x/tools/cmd/cover
  - cd $HOME/gopath/src/github.com/jubnzv/go-tmux
  - yes "yes" | tmux new-session -d || true # $? == 0
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
